sharedurllist/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.views import login
from views import *

urlpatterns = patterns('',
    url(r'^$', main, name='main'),
    url(r'^bookmarklet/$', bookmarklet, name='bookmarklet'),
    url(r'^token/$', token, name='token'),
    url(r'^delete/device/$', delete_device, name='delete_device'),
    url(r'^delete/url/$', delete_url, name='delete_url'),
    url(r'^accounts/login/$', login, name='login'),
)

sharedurllist/models.py
from django.db import models
from django.contrib.auth.models import User


class Device(models.Model):
    class Meta:
        unique_together = ("user", "name")
    user = models.ForeignKey(User)
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name


class Token(models.Model):
    user = models.ForeignKey(User)
    device = models.ForeignKey(Device)
    token = models.CharField(max_length=36, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    last_used = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.token


class Url(models.Model):
    user = models.ForeignKey(User)
    device = models.ForeignKey(Device)
    created = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __unicode__(self):
        return self.content

sharedurllist/views.py
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

import uuid

from models import *
from errormessages import *
from api import *


def get_device(user, devicename):
    """
        helper function to get or create a device for a given name
        @type user: User object
        @type devicename: String
    """
    try:
        device = Device.objects.get(name=devicename)
    except Device.DoesNotExist:
        device = Device(user=user, name=devicename)
        device.save()
    return device


def main(request):
    """
        main view, for the webinterface, as for the api,
            as the api uses only one url with GET-Parameters.
    """
    if "api" in request.GET:
        return api(request)
    else:
        return home(request)


def bookmarklet(request):
    """
        add a URL via bookmarklet, or list all bookmarklets of the user,
            when no url is given.
    """
    template_dict = {"view": "bookmarklet"}
    status = ""
    if len(request.GET) == 0:
        if not request.user.is_authenticated():
            return login_required(bookmarklet)(request)
        else:
            tokens = Token.objects.filter(user=request.user)
            if len(tokens) == 0:
                status = "You have not created any tokens, yet."
                template_dict["success"] = False
            template_dict["tokens"] = tokens
    else:
        try:
            token = Token.objects.get(token=request.GET.get("token"))
            if token.is_active:
                url = request.GET.get("url")
                if Url.objects.filter(user=token.user, device=token.device,
                                      content=url).count() > 0:
                    status = "Url already in list"
                else:
                    Url(user=token.user, device=token.device,
                        content=url).save()
                    status = "URL added."
                    template_dict['success'] = True
                    template_dict['url'] = url
                    template_dict['token'] = token
            else:
                template_dict['success'] = False
                status = "Token inactive"
        except Token.DoesNotExist:
            status = "invalid token."
            template_dict['success'] = False

    template_dict["status"] = status
    return render(request, "bookmarklet.html", template_dict)


@login_required
def home(request):
    """
        main view of the webinterface, listing devices with their urls
            and the token list.
    """
    return render(request, "home.html", {
        "view": "home",
        "tokens": Token.objects.filter(user=request.user),
        "devices": Device.objects.all(),
    })


@login_required
def delete_device(request):
    """
        delete device view
        needed POST-Parameters:
        - device_id with the id of the device.
            and redirects back to the main view.
    """
    if "device_id" in request.POST:
        try:
            Device.objects.get(id=request.POST.get("device_id", 0)).delete()
        except Device.DoesNotExist:
            pass
    return redirect(reverse(main))


def delete_url(request):
    """
        view for deleting an url
        needed POST-Parameters:

            redirects to main view with the current_tab
    """
    if "url" in request.POST:
        url = get_object_or_404(Url, id=request.POST.get("url"))
        url.delete()
    return redirect(reverse(main) + request.POST.get("current_tab", ""))


@login_required
def token(request):
    """
        creates, enables, disables or deletes a token
        needed POST-Parameters:
        - one of enable/disable/create/delete set
        - device: (only for create) devicename, to create the token for
        - token: (for all other calls) token to be enabled/disabled/deleted
        redirects to the main view, with the token-tab opened
    """
    POST = request.POST

    if POST.get("create") and POST.get("device"):
        device = get_device(request.user, POST.get("device"))
        Token(user=request.user, device=device, token=uuid.uuid4()).save()
    else:
        token = get_object_or_404(Token, token=POST.get("token"))

    if POST.get("disable"):
        token.is_active = False
        token.save()
    elif POST.get("enable"):
        token.is_active = True
        token.save()
    elif POST.get("delete"):
        token.delete()
    return redirect(reverse(main) + "#urltab_special-tokens")

sharedurllist/templates/base.html
<!DOCTYPE html>
<html>
    <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{{STATIC_URL}}bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen" />
    <script src="{{ STATIC_URL }}js/jquery.js"></script>
    <link href="{{STATIC_URL}}style.css" rel="stylesheet" />
    <style>
        {% block extrastyle %}{% endblock %}
    </style>
    {% block extrahead %}{% endblock %}
</head>
<body>
    <script src="{{STATIC_URL}}bootstrap/js/bootstrap.min.js"></script>
    {% include "snippets/tab-bar.html" %}
    <div class="row-fluid container">
        <div class="span10 offset1">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <script>
        $(".bookmarklet").each(function(){
            $(this).attr("href", "javascript:void(window.open('"+window.location.protocol+"//"+window.location.host+"{% url 'sharedurllist.views.bookmarklet' %}?token="+$(this).attr("data-token")+"&url='+escape(window.location.href)))")
        });
    </script>
</body>
</html>

sharedurllist/templates/bookmarklet.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}
{% block title %}Bookmarklet{% endblock %}
{% block content %}
<div class="well">
    {% if status %}
        {{status}}
        <br />
    {% endif %}
    {% if tokens %}
        <table class="table table-bordered table-hover table-condensed" style="background-color: white">
        <tr>
            <th> Bookmarklet </th>
            <th> Active</th>
            <th> Token </th>
        </tr>
        {% for token in tokens %}
            <tr class="{% if token.is_active %}success{% else %}error{% endif %}">
                <td>
                    <h4>
                        <a class="bookmarklet" href="" data-token="{{ token.token }}">add to List</a> ({{ token.device.name }})
                    </h4>
                </td>
                <td class="active_{% if token.is_active %}yes{% else %}no{% endif %}">
                    {% if token.is_active %}yes{% else %}no{% endif %}
                </td>
                <td>
                    <span class="token" data-token="{{ token.token }}">{{ token.token }}</span>
                </td>
            </tr>
        {% endfor %}
    {% endif %}
    {% if success %}
        <a href="{{ url }}">{{ url }}</a>
        <br />
        <a class="btn" href="{{ url }}">Back to Page</a>
        <a class="btn" href="{% url 'sharedurllist.views.main' %}#urltab_{{ token.device.name }}">Go to URL-List</a>
    {% endif %}
</div>
{% endblock %}

sharedurllist/templates/home.html
{% extends "base.html" %}
{% load url from future %}
{% block title %}Urllists{% endblock %}
{% block pagetitle %}Urllists{% endblock %}
{% block content %}

<div id="urltabs">
    <div class="tabbable">
        <div class="tab-content">
            {% for device in devices %}
                {% include "snippets/device-tab.html" %}
            {% endfor %}
            {% include "snippets/tokens-tab.html" %}
        </div>
    </div>
</div>

<script>
    $("span.token").click(function(){
        $(this).text($(this).data("token"));
    });
    var currentUrlTab=0;
    var hashParameters = location.hash.substr(1).split("&");
    for(i=0;i<hashParameters.length;i++){
        var parts=hashParameters[i].split("_");
        if(parts.length==2 && parts[0] == "urltab"){
            currentUrlTab=parts[1];
            $("a[data-devicename="+currentUrlTab+"]").tab("show");
        }
    }
    $(".urltab").click(function(){window.location.hash = "urltab_" + $(this).attr("data-devicename")})
    $("form[action='{% url "sharedurllist.views.delete_url" %}'] input[type=submit]").each(function(i, e){
        $(e).hide();
        var button = $("<input type='button' class='btn' value='del'>").bind("click", function(){
            var form = $(e).parent();
            var action = form.attr("action");
            var data = {}
            form.find("input").each(function(idx, obj){
                form_field = $(obj);
                data[form_field.attr("name")] = form_field.val();
            })
            form.parent().hide()
            ajaxRequest = $.ajax(action, {
                "type": "post",
                "data": data,
                "error": function(){form.parent().show()}
            });
        });
        $(e).after(button)
    });
</script>
{% endblock %}

sharedurllist/templates/snippets/device-tab.html
<div class="urltab tab-pane well {% if forloop.counter == 1 %}active{% endif %}" id="urltab_{{device.name}}">
    <table class="table urllist">
        {% for theurl in device.url_set.all %}
        <tr>
            <td>
                <form class="pull-left" method="post" action="{% url "sharedurllist.views.delete_url" %}" style="display: inline">
                    {% csrf_token %}
                    <input type="hidden" name="url" value="{{theurl.id}}" />
                        <input type="hidden" name="current_tab" value="#urltab_{{ device.name }}" class="current_tab" />
                        <input type="submit" name="delete" value="del" class="btn" />
                </form>
                <p>
                    {{ theurl.content }}<br />
                    <small>({{ theurl.created }})</small>
                </p>
            </td>
        </tr>
        {% endfor %}
        <tr>
            <td>
                <form method="post" action="{% url "sharedurllist.views.delete_device" %}" style="text-align: right">
                    {% csrf_token %}
                    <input type="hidden" name="device_id" value="{{device.id}}" class="btn" />
                    <input type="submit" name="delete" value="delete device" class="btn" />
                </form>
            </td>
        </tr>
    </table>
</div>

sharedurllist/templates/snippets/device-tabs.html
{% for device in devices %}
<li class="{% if forloop.counter == 1 and view == "home"  %}active{% endif %}">
    <a class="urltab" href="{% url "sharedurllist.views.main" %}#urltab_{{ device.name }}" data-devicename="{{ device.name }}"{% if view == "home" %} data-toggle="tab"{% endif %}>{{device.name}}</a>
</li>
{% endfor %}

sharedurllist/templates/snippets/tab-bar.html
{% load url from future %}
<div class="navbar">
    <div class="navbar-inner">
        <ul class="nav nav-tabs" data-tabs="tabs">
            <a href="{% url 'sharedurllist.views.main' %}'" class="brand">SharedUrlList</a>
            <li class="{% if view == "bookmarklet" %}active{% endif %}">
                    <a 
                        class="urltab"
                        {% if view != "bookmarklet" %}
                            href="{% url "sharedurllist.views.bookmarklet" %}"
                        {% else %}
                            data-toggle="tab"
                        {% endif %} 
                        data-devicename="special-bookmarklet">
                        Bookmarklet
                    </a>
            </li>
                {% include "snippets/device-tabs.html" %}
            <li class="divider-vertical navbar-divider">
            </li>
            <li>
                <a class="urltab" href="{% url 'sharedurllist.views.main' %}#urltab_special-tokens" {%if view == "home" %}data-toggle="tab"{% endif %} data-devicename="special-tokens">Token-List</a>
            </li>
        </ul>
    </div>
</div>

sharedurllist/templates/snippets/tokens-tab.html
<div class="tab-pane well {% if forloop.counter == 1 %}active{% endif %}" id="urltab_special-tokens">
    <table class="table table-bordered table-hover table-condensed" style="background-color: white">
        <tr>
            <th> Device Name </th>
            <th> Token </th>
            <th> Created </th>
            <th> Last_Used </th>
            <th> Active </th>
            <th> Actions </th>
        </tr>
        {% for token in tokens %}
        <tr class="{% if token.is_active %}success{% else %}error{% endif %}">
            <td> {{ token.device.name }} </td>
            <td>
                <span class="token" data-token="{{ token.token }}">{{ token.token|truncatechars:12 }}</a>
            </td>
            <td> {{ token.created }} </td>
            <td> {{ token.last_used }} </td>
            <td class="active_{% if token.is_active %}yes{% else %}no{% endif %}">
                {% if token.is_active %}yes{% else %}no{% endif %}
            </td>
            <td>
                <form method="post" action="{% url "sharedurllist.views.token" %}">
                    {% csrf_token %}
                    <input type="hidden" name="token" value="{{ token.token }}" />
                    {% if token.is_active %}
                        <input type="submit" name="disable" value="disable" class="btn" />
                    {% else %}
                        <input type="submit" name="enable" value="enable" class="btn" />
                    {% endif %}
                    <input type="submit" name="delete" value="delete" class="btn" />
                    <br />
                    Bookmarklet: <a href="" data-token="{{ token.token }}" class="bookmarklet">add to List</a>
                </form>
            </td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="6">
                <form method="post" action="{% url "sharedurllist.views.token" %}" class="pull-right">
                    {% csrf_token %}
                    <input type="text" name="device" placeholder="device name" />
                    <input type="submit" name="create" value="create" class="btn" />
                </form>
            </td>
        </tr>
    </table>
</div>